
title             : "Project documentation"
project_name      : "Example"
description: >-
  Project description
url               : # http://example.com
base_url          : # /docs
repository        : # username/repo-name

permalink         : /:categories/:title/

doc_collection    : docs
doc_version       : 1.0.0

getting_started: >-
  Take a look on the useful materials below.
  Start by checking "the System Overview" to get a big picture of the project.
  Don't forget to check "Development Guidelines".
  Find more by exploring navigation on the left.

links:
  repos:
    - name  : Web app repository
      icon  : "fab fa-github" # Use fontawesome v6
      url   : https://bitbucket.org/
    - name  : Backend repository
      icon  : "fab fa-bitbucket" # Use fontawesome v6
      url   : https://bitbucket.org/
    - name  : Docs repository
      icon  : "fab fa-gitlab" # Use fontawesome v6
      url   : https://bitbucket.org/
  useful:
    - name  : System overview
      icon  : "fas fa-project-diagram"
      url   : /architecture/
    - name  : Architecture
      icon  : "fas fa-clipboard-list"
      url   : /architecture/
    - name  : Development Guidelines
      icon  : "fas fa-pencil-alt"
      url   : /architecture/

sass:
  sass_dir        : _sass
  style           : compressed

plugins:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

include:
  - .htaccess
  - _pages
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Gemfile
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /test
  - /docs

# contributors  :
